<a href="https://colab.research.google.com/github/drfperez/openair/blob/main/SIVIC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd
import time
import urllib.parse
from google.colab import files
from datetime import datetime
import numpy as np

def descarregar_sivic(any_inici=None, any_fi=None, codi_regio=None, codi_abs=None):
    """
    Descarrega dades de SIVIC i les processa a format openair wide.
    """
    base_url = "https://analisi.transparenciacatalunya.cat/resource/fa7i-d8gc.json"
    limit = 50000
    offset = 0
    tots_els_dades = []

    # Construir condicions SoQL
    condicions = []

    if codi_regio:
        condicions.append(f"codi_regio='{codi_regio}'")

    if codi_abs:
        condicions.append(f"codi_abs='{codi_abs}'")

    # Filtre per Data (Rang d'anys)
    if any_inici:
        if any_fi is None:
            any_fi = any_inici
        data_inici = f"{any_inici}-01-01T00:00:00"
        data_fi = f"{any_fi + 1}-01-01T00:00:00"
        condicions.append(f"data >= '{data_inici}' AND data < '{data_fi}'")

    where_clause = " AND ".join(condicions) if condicions else "1=1"

    print("🚀 Iniciant descàrrega de dades SIVIC...")
    print(f"   Filtres -> Anys: {any_inici} a {any_fi}, Regió: {codi_regio}, ABS/CAP: {codi_abs}")

    while True:
        # Ordenem per data
        query = f"?$where={where_clause}&$limit={limit}&$offset={offset}&$order=data ASC"
        url_neta = base_url + urllib.parse.quote(query, safe='?=&-:T')

        try:
            df_bloc = pd.read_json(url_neta)

            if df_bloc.empty:
                break

            tots_els_dades.append(df_bloc)
            offset += limit

            # Mostrem progrés
            if 'data' in df_bloc.columns:
                ultima_data = df_bloc['data'].iloc[-1]
                print(f"📥 {offset} registres processats... Data actual: {str(ultima_data)[:10]}")
            else:
                print(f"📥 {offset} registres processats...")

            time.sleep(0.3)

        except Exception as e:
            print(f"⚠️ Error durant la descàrrega: {e}")
            break

    if tots_els_dades:
        df_final = pd.concat(tots_els_dades, ignore_index=True)

        # Convertim columnes de data
        if 'data' in df_final.columns:
            df_final['data'] = pd.to_datetime(df_final['data'])

        print(f"\n✅ ÈXIT: {len(df_final)} registres descarregats.")
        if not df_final.empty and 'data' in df_final.columns:
            print(f"📅 Període: {df_final['data'].min().date()} fins a {df_final['data'].max().date()}")

        # Convertir casos a numèric
        df_final['casos'] = pd.to_numeric(df_final['casos'], errors='coerce')

        # Agregar sumant casos per data i diagnostic (sumant sobre sexe, edat, socio, etc.)
        df_agg = df_final.groupby(['data', 'diagnostic'])['casos'].sum().reset_index()

        # Pivotar a format wide
        df_pivot = df_agg.pivot(index='data', columns='diagnostic', values='casos')

        # Omplir NaN amb 0
        df_pivot = df_pivot.fillna(0)

        # Ordenar l'índex
        df_pivot = df_pivot.sort_index()

        # Reset index i renombrar
        df_wide = df_pivot.reset_index()
        df_wide.rename(columns={'data': 'date'}, inplace=True)

        # Renombrar columnes a noms curts si cal (per openair)
        var_names = {
            'Altres IRA': 'ira_other',
            'Bronquiolitis': 'bronq',
            'COVID-19': 'covid',
            'Escarlatina': 'escar',
            'Faringoamigdalitis': 'far_amig',
            'Faringoamigdalitis estreptocòccica': 'far_amig_estrep',
            'Grip': 'grip',
            'Impetigen': 'impet',
            'Pneumònia': 'pneum'
        }
        df_wide.rename(columns=var_names, inplace=True)

        # Nom de fitxer dinàmic
        nom_fitxer = f"SIVIC_openair_wide"
        if codi_regio: nom_fitxer += f"_{codi_regio}"
        if codi_abs: nom_fitxer += f"_{codi_abs}"
        if any_inici: nom_fitxer += f"_{any_inici}"
        if any_fi and any_fi != any_inici: nom_fitxer += f"-{any_fi}"
        nom_fitxer += ".csv"

        df_wide.to_csv(nom_fitxer, index=False, date_format='%Y-%m-%d')
        files.download(nom_fitxer)

        return df_wide
    else:
        print("❌ No s'han trobat dades amb aquests filtres.")
        return None

# --- INTERACCIÓ AMB L'USUARI ---

print("--- DESCARREGADOR DADES SIVIC (FORMAT OPENAIR WIDE) ---")
print("ℹ️  Utilitza codis de regions (ex: 76 per Metropolitana Nord) i CAPs (ex: 310).")
print("   Deixa buit per seleccionar tots.")
print("----------------------------------------------------")

any_inici_usuari = input("Introdueix l'any inici (deixa buit per tots): ").strip()
any_fi_usuari = input("Introdueix l'any fi (deixa buit si igual a inici): ").strip()
codi_regio_usuari = input("Introdueix Codi Regió (deixa buit per tots): ").strip()
codi_abs_usuari = input("Introdueix Codi ABS/CAP (deixa buit per tots): ").strip()

# Processar inputs
any_inici_usuari = int(any_inici_usuari) if any_inici_usuari.isdigit() else None
any_fi_usuari = int(any_fi_usuari) if any_fi_usuari.isdigit() else None
codi_regio_usuari = codi_regio_usuari if codi_regio_usuari else None
codi_abs_usuari = codi_abs_usuari if codi_abs_usuari else None

# Executar funció
df_resultat = descarregar_sivic(any_inici_usuari, any_fi_usuari, codi_regio_usuari, codi_abs_usuari)

--- DESCARREGADOR DADES SIVIC (FORMAT OPENAIR WIDE) ---
ℹ️  Utilitza codis de regions (ex: 76 per Metropolitana Nord) i CAPs (ex: 310).
   Deixa buit per seleccionar tots.
----------------------------------------------------
Introdueix l'any inici (deixa buit per tots):
Introdueix l'any fi (deixa buit si igual a inici):
Introdueix Codi Regió (deixa buit per tots): 76
Introdueix Codi ABS/CAP (deixa buit per tots): 310
🚀 Iniciant descàrrega de dades SIVIC...
   Filtres -> Anys: None a None, Regió: 76, ABS/CAP: 310
📥 50000 registres processats... Data actual: 2020-12-28
📥 100000 registres processats... Data actual: 2026-02-08

✅ ÈXIT: 92369 registres descarregats.
📅 Període: 2011-10-03 fins a 2026-02-08

In [ ]:
import pandas as pd
import time
import urllib.parse
from google.colab import files
from datetime import datetime
import numpy as np

# Llistat de regions i CAPs
base_url = "https://analisi.transparenciacatalunya.cat/resource/fa7i-d8gc.json"

# Per regions
query_regions = "?$select=codi_regio,nom_regio&$group=codi_regio,nom_regio&$order=codi_regio ASC&$limit=1000"
url_regions = base_url + urllib.parse.quote(query_regions, safe='?=&$')
df_regions = pd.read_json(url_regions)
df_regions.to_csv('regions.csv', index=False)
files.download('regions.csv')

# Per ABS/CAPs
query_abs = "?$select=codi_regio,nom_regio,codi_abs,nom_abs&$group=codi_regio,nom_regio,codi_abs,nom_abs&$order=codi_regio,codi_abs ASC&$limit=100000"
url_abs = base_url + urllib.parse.quote(query_abs, safe='?=&$')
df_abs = pd.read_json(url_abs)
df_abs.to_csv('caps.csv', index=False)
files.download('caps.csv')

# Mostrar completament
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

display(df_regions)
display(df_abs)

def descarregar_sivic(any_inici=None, any_fi=None, codi_regio=None, codi_abs=None):
    """
    Descarrega dades de SIVIC i les processa a format openair wide.
    """
    base_url = "https://analisi.transparenciacatalunya.cat/resource/fa7i-d8gc.json"
    limit = 50000
    offset = 0
    tots_els_dades = []

    # Construir condicions SoQL
    condicions = []

    if codi_regio:
        condicions.append(f"codi_regio='{codi_regio}'")

    if codi_abs:
        condicions.append(f"codi_abs='{codi_abs}'")

    # Filtre per Data (Rang d'anys)
    if any_inici:
        if any_fi is None:
            any_fi = any_inici
        data_inici = f"{any_inici}-01-01T00:00:00"
        data_fi = f"{any_fi + 1}-01-01T00:00:00"
        condicions.append(f"data >= '{data_inici}' AND data < '{data_fi}'")

    where_clause = " AND ".join(condicions) if condicions else "1=1"

    print("🚀 Iniciant descàrrega de dades SIVIC...")
    print(f"   Filtres -> Anys: {any_inici} a {any_fi}, Regió: {codi_regio}, ABS/CAP: {codi_abs}")

    while True:
        # Ordenem per data
        query = f"?$where={where_clause}&$limit={limit}&$offset={offset}&$order=data ASC"
        url_neta = base_url + urllib.parse.quote(query, safe='?=&-:T')

        try:
            df_bloc = pd.read_json(url_neta)

            if df_bloc.empty:
                break

            tots_els_dades.append(df_bloc)
            offset += limit

            # Mostrem progrés
            if 'data' in df_bloc.columns:
                ultima_data = df_bloc['data'].iloc[-1]
                print(f"📥 {offset} registres processats... Data actual: {str(ultima_data)[:10]}")
            else:
                print(f"📥 {offset} registres processats...")

            time.sleep(0.3)

        except Exception as e:
            print(f"⚠️ Error durant la descàrrega: {e}")
            break

    if tots_els_dades:
        df_final = pd.concat(tots_els_dades, ignore_index=True)

        # Convertim columnes de data
        if 'data' in df_final.columns:
            df_final['data'] = pd.to_datetime(df_final['data'])

        print(f"\n✅ ÈXIT: {len(df_final)} registres descarregats.")
        if not df_final.empty and 'data' in df_final.columns:
            print(f"📅 Període: {df_final['data'].min().date()} fins a {df_final['data'].max().date()}")

        # Convertir casos a numèric
        df_final['casos'] = pd.to_numeric(df_final['casos'], errors='coerce')

        # Agregar sumant casos per data i diagnostic (sumant sobre sexe, edat, socio, etc.)
        df_agg = df_final.groupby(['data', 'diagnostic'])['casos'].sum().reset_index()

        # Pivotar a format wide
        df_pivot = df_agg.pivot(index='data', columns='diagnostic', values='casos')

        # Omplir NaN amb 0
        df_pivot = df_pivot.fillna(0)

        # Ordenar l'índex
        df_pivot = df_pivot.sort_index()

        # Reset index i renombrar
        df_hourly = df_pivot.reset_index()
        df_hourly.rename(columns={'data': 'date'}, inplace=True)

        # Renombrar columnes a noms curts si cal (per openair)
        var_names = {
            'Altres IRA': 'ira_other',
            'Bronquiolitis': 'bronq',
            'COVID-19': 'covid',
            'Escarlatina': 'escar',
            'Faringoamigdalitis': 'far_amig',
            'Faringoamigdalitis estreptocòccica': 'far_amig_estrep',
            'Grip': 'grip',
            'Impetigen': 'impet',
            'Pneumònia': 'pneum'
        }
        df_hourly.rename(columns=var_names, inplace=True)

        # Nom de fitxer dinàmic
        nom_fitxer = f"SIVIC_openair_daily"
        if codi_regio: nom_fitxer += f"_{codi_regio}"
        if codi_abs: nom_fitxer += f"_{codi_abs}"
        if any_inici: nom_fitxer += f"_{any_inici}"
        if any_fi and any_fi != any_inici: nom_fitxer += f"-{any_fi}"
        nom_fitxer += ".csv"

        df_hourly.to_csv(nom_fitxer, index=False, date_format='%Y-%m-%d %H:%M:%S')
        files.download(nom_fitxer)

        return df_hourly
    else:
        print("❌ No s'han trobat dades amb aquests filtres.")
        return None

# --- INTERACCIÓ AMB L'USUARI ---

print("--- DESCARREGADOR DADES SIVIC (OPENAIR FORMAT) ---")
print("ℹ️  Utilitza els codis de regions i CAPs dels CSV descarregats.")
print("   Si deixes buit, selecciona tots.")
print("----------------------------------------------------")

any_inici_usuari = input("Introdueix l'any inici (deixa buit per tots): ").strip()
any_fi_usuari = input("Introdueix l'any fi (deixa buit si igual a inici): ").strip()
codi_regio_usuari = input("Introdueix Codi Regió (ex: 76): ").strip()
codi_abs_usuari = input("Introdueix Codi ABS/CAP (ex: 310): ").strip()

# Processar inputs
any_inici_usuari = int(any_inici_usuari) if any_inici_usuari.isdigit() else None
any_fi_usuari = int(any_fi_usuari) if any_fi_usuari.isdigit() else None
codi_regio_usuari = codi_regio_usuari if codi_regio_usuari else None
codi_abs_usuari = codi_abs_usuari if codi_abs_usuari else None

# Executar funció
df_resultat = descarregar_sivic(any_inici_usuari, any_fi_usuari, codi_regio_usuari, codi_abs_usuari)

    codi_regio                     nom_regio
0            0                 No disponible
1           61                        Lleida
2           62             Camp de Tarragona
3           63              Terres de l'Ebre
4           64                        Girona
5           67             Catalunya Central
6           70                       Penedès
7           71            Alt Pirineu i Aran
8           75   Barcelona Metropolitana Sud
9           76  Barcelona Metropolitana Nord
10          79              Barcelona Ciutat

,codi_regio,nom_regio,codi_abs,nom_abs
0,0,No disponible,0,No disponible
1,61,Lleida,1,Agramunt
2,61,Lleida,2,Alcarràs
3,61,Lleida,3,Alfarràs - Almenar
4,61,Lleida,12,Artesa de Segre
5,61,Lleida,14,Balaguer
6,61,Lleida,81,Bellpuig
7,61,Lleida,86,Les Borges Blanques
8,61,Lleida,106,Cervera - la Segarra
9,61,Lleida,129,La Granadella
10,61,Lleida,135,Lleida - 1 Centre Històric - Rambla de Ferran
11,61,Lleida,136,Lleida - 2 Ronda - Mariola
12,61,Lleida,137,Lleida - 3 Eixample
13,61,Lleida,138,Lleida - 4 Balàfia - Pardinyes
14,61,Lleida,139,Lleida - 5 Cappont
15,61,Lleida,140,Lleida - 6 Bordeta - Magraners
16,61,Lleida,141,Lleida rural - 1 Nord
17,61,Lleida,161,Pla d'Urgell
18,61,Lleida,181,Ponts
19,61,Lleida,232,Seròs
20,61,Lleida,245,Tàrrega
21,61,Lleida,329,Lleida rural - 2 Sud
22,61,Lleida,334,Almacelles
23,61,Lleida,379,Lleida - 7 Onze de Setembre
24,61,Lleida,408,Guissona - La Segarra
25,62,Camp de Tarragona,87,Les Borges del Camp
26,62,Camp de Tarragona,91,Cambrils
27,62,Camp de Tarragona,107,Constantí
28,62,Camp de Tarragona,112,Cornudella de Montsant
29,62,Camp de Tarragona,118,Falset
30,62,Camp de Tarragona,162,Montblanc
31,62,Camp de Tarragona,163,Mont-roig del Camp
32,62,Camp de Tarragona,166,El Morell
33,62,Camp de Tarragona,188,Riudoms
34,62,Camp de Tarragona,239,Tarragona - 1
35,62,Camp de Tarragona,240,Tarragona - 2
36,62,Camp de Tarragona,241,Tarragona - 3
37,62,Camp de Tarragona,242,Tarragona - 4
38,62,Camp de Tarragona,243,Tarragona - 5
39,62,Camp de Tarragona,244,Tarragona - 6
40,62,Camp de Tarragona,257,Torredembarra
41,62,Camp de Tarragona,262,Alt Camp Est
42,62,Camp de Tarragona,263,Valls urbà
43,62,Camp de Tarragona,303,Reus - 1
44,62,Camp de Tarragona,304,Reus - 2
45,62,Camp de Tarragona,305,Reus - 3
46,62,Camp de Tarragona,306,Reus - 4
47,62,Camp de Tarragona,307,Reus - 5
48,62,Camp de Tarragona,324,Vandellòs i l'Hospitalet de l'Infant
49,62,Camp de Tarragona,333,Alt Camp Oest
50,62,Camp de Tarragona,339,Salou
51,62,Camp de Tarragona,340,Vila-seca
52,62,Camp de Tarragona,352,Tarragona - 7
53,62,Camp de Tarragona,354,La Selva del Camp
54,62,Camp de Tarragona,364,Tarragona - 8
55,63,Terres de l'Ebre,4,Amposta
56,63,Terres de l'Ebre,113,Deltebre
57,63,Terres de l'Ebre,120,Flix
58,63,Terres de l'Ebre,165,Móra la Nova - Móra d'Ebre
59,63,Terres de l'Ebre,178,L'Ametlla de Mar - El Perelló
60,63,Terres de l'Ebre,206,La Ràpita - Alcanar
61,63,Terres de l'Ebre,246,Terra Alta
62,63,Terres de l'Ebre,255,Tortosa - 1 Est
63,63,Terres de l'Ebre,256,Tortosa - 2 Oest
64,63,Terres de l'Ebre,260,Ulldecona
65,63,Terres de l'Ebre,328,L'Aldea - Camarles - l'Ampolla
66,64,Girona,5,Anglès
67,64,Girona,8,Arbúcies - Sant Hilari
68,64,Girona,15,Banyoles
69,64,Girona,80,Bàscara
70,64,Girona,83,Besalú
71,64,Girona,84,La Bisbal d'Empordà
72,64,Girona,85,Blanes
73,64,Girona,90,Calella
74,64,Girona,92,Camprodon
75,64,Girona,93,Canet de Mar
76,64,Girona,100,Cassà de la Selva
77,64,Girona,101,Celrà
78,64,Girona,114,L'Escala
79,64,Girona,119,Figueres
80,64,Girona,124,Girona - 1
81,64,Girona,125,Girona - 2
82,64,Girona,126,Girona - 3
83,64,Girona,127,Girona - 4
84,64,Girona,133,La Jonquera
85,64,Girona,134,Llançà
86,64,Girona,142,Lloret de Mar
87,64,Girona,143,Malgrat de Mar
88,64,Girona,171,Olot
89,64,Girona,172,Palafrugell
90,64,Girona,173,Palamós
91,64,Girona,177,Peralada
92,64,Girona,187,Ripoll - Sant Joan de les Abadesses
93,64,Girona,189,Roses
94,64,Girona,199,Salt
95,64,Girona,208,Sant Feliu de Guíxols
96,64,Girona,221,Santa Coloma de Farners
97,64,Girona,231,Sarrià de Ter
98,64,Girona,234,Sils - Vidreres - Maçanet de la Selva
99,64,Girona,258,Torroella de Montgrí
100,64,Girona,267,Vilafant
101,64,Girona,325,Pineda de Mar
102,64,Girona,330,Breda - Hostalric
103,64,Girona,336,Tordera
104,64,Girona,343,Ribes de Freser - Campdevànol
105,64,Girona,346,Sant Joan les Fonts
106,64,Girona,347,Vall d'en Bas
107,67,Catalunya Central,11,Artés
108,67,Catalunya Central,82,Berga
109,67,Catalunya Central,88,Calaf
110,67,Catalunya Central,96,Cardona
111,67,Catalunya Central,98,Montserrat
112,67,Catalunya Central,102,Centelles
113,67,Catalunya Central,128,Baix Berguedà
114,67,Catalunya Central,130,Alt Berguedà
115,67,Catalunya Central,144,Manlleu
116,67,Catalunya Central,145,Manresa - 1
117,67,Catalunya Central,146,Manresa - 2
118,67,Catalunya Central,147,Manresa - 3
119,67,Catalunya Central,148,Manresa - 4
120,67,Catalunya Central,159,Moià
121,67,Catalunya Central,167,Navàs - Balsareny
122,67,Catalunya Central,185,Lluçanès
123,67,Catalunya Central,200,Sallent
124,67,Catalunya Central,211,Navarcles - Sant Fruitós de Bages
125,67,Catalunya Central,212,Sant Hipólit de Voltregà
126,67,Catalunya Central,215,Sant Joan de Vilatorrada
127,67,Catalunya Central,217,Sant Quirze de Besora
128,67,Catalunya Central,219,Sant Vicenç de Castellet
129,67,Catalunya Central,236,El Solsonès
130,67,Catalunya Central,237,Súria
131,67,Catalunya Central,238,Santa Eugènia de Berga
132,67,Catalunya Central,253,Tona
133,67,Catalunya Central,254,Vall del Ges
134,67,Catalunya Central,350,Vic - 1 Nord
135,67,Catalunya Central,351,Vic - 2 Sud
136,67,Catalunya Central,377,Roda de Ter
137,67,Catalunya Central,409,Santpedor
138,70,Penedès,13,El Vendrell
139,70,Penedès,131,Anoia rural
140,70,Penedès,218,Sant Sadurní d'Anoia
141,70,Penedès,228,Santa Coloma de Queralt
142,70,Penedès,229,Santa Margarida de Montbui
143,70,Penedès,235,Sitges
144,70,Penedès,269,Vilanova del Camí
145,70,Penedès,314,Baix Penedès - Interior
146,70,Penedès,316,Vilanova i la Geltrú - 1
147,70,Penedès,317,Vilanova i la Geltrú - 2
148,70,Penedès,337,Capellades
149,70,Penedès,338,Piera
150,70,Penedès,357,Calafell
151,70,Penedès,359,Cubelles - Cunit
152,70,Penedès,371,Igualada - 1
153,70,Penedès,372,Igualada - 2
154,70,Penedès,380,Vilanova i la Geltrú - 3
155,70,Penedès,393,Ribes - Olivella
156,70,Penedès,394,Roquetes - Canyelles
157,70,Penedès,397,Vilafranca del Penedès - 1
158,70,Penedès,398,Vilafranca del Penedès - 2
159,70,Penedès,405,Penedès rural - Est
160,70,Penedès,406,Penedès rural - Oest
161,71,Alt Pirineu i Aran,7,Aran
162,71,Alt Pirineu i Aran,103,Cerdanya
163,71,Alt Pirineu i Aran,169,Alt Urgell Sud
164,71,Alt Pirineu i Aran,174,Pallars Sobirà
165,71,Alt Pirineu i Aran,179,La Pobla de Segur
166,71,Alt Pirineu i Aran,180,Alta Ribagorça
167,71,Alt Pirineu i Aran,233,La Seu d'Urgell
168,71,Alt Pirineu i Aran,259,Tremp
169,75,Barcelona Metropolitana Sud,108,Cornellà de Llobregat - 1
170,75,Barcelona Metropolitana Sud,109,Cornellà de Llobregat - 2
171,75,Barcelona Metropolitana Sud,110,Cornellà de Llobregat - 3
172,75,Barcelona Metropolitana Sud,111,Cornellà de Llobregat - 4
173,75,Barcelona Metropolitana Sud,115,Esparreguera
174,75,Barcelona Metropolitana Sud,116,Esplugues de Llobregat - 1
175,75,Barcelona Metropolitana Sud,117,Esplugues de Llobregat - 2
176,75,Barcelona Metropolitana Sud,122,Gavà - 1
177,75,Barcelona Metropolitana Sud,123,Gavà - 2
178,75,Barcelona Metropolitana Sud,149,Martorell
179,75,Barcelona Metropolitana Sud,160,Molins de Rei
180,75,Barcelona Metropolitana Sud,168,Olesa de Montserrat
181,75,Barcelona Metropolitana Sud,182,El Prat de Llobregat - 1
182,75,Barcelona Metropolitana Sud,183,El Prat de Llobregat - 2
183,75,Barcelona Metropolitana Sud,184,El Prat de Llobregat - 3
184,75,Barcelona Metropolitana Sud,201,Sant Andreu de la Barca
185,75,Barcelona Metropolitana Sud,202,Sant Boi de Llobregat - 1
186,75,Barcelona Metropolitana Sud,203,Sant Boi de Llobregat - 2
187,75,Barcelona Metropolitana Sud,204,Sant Boi de Llobregat - 3
188,75,Barcelona Metropolitana Sud,205,Sant Boi de Llobregat - 4
189,75,Barcelona Metropolitana Sud,209,Sant Feliu de Llobregat - 1
190,75,Barcelona Metropolitana Sud,210,Sant Feliu de Llobregat - 2
191,75,Barcelona Metropolitana Sud,213,Sant Joan Despí - 1
192,75,Barcelona Metropolitana Sud,214,Sant Joan Despí - 2
193,75,Barcelona Metropolitana Sud,216,Sant Just Desvern
194,75,Barcelona Metropolitana Sud,261,Vallirana
195,75,Barcelona Metropolitana Sud,265,Viladecans - 1
196,75,Barcelona Metropolitana Sud,266,Viladecans - 2
197,75,Barcelona Metropolitana Sud,288,L'Hospitalet de Llobregat - 01 Centre
198,75,Barcelona Metropolitana Sud,289,L'Hospitalet de Llobregat - 02 Sant Josep
199,75,Barcelona Metropolitana Sud,290,L'Hospitalet de Llobregat - 03 Colblanc
200,75,Barcelona Metropolitana Sud,291,L'Hospitalet de Llobregat - 04 Torrassa
201,75,Barcelona Metropolitana Sud,292,L'Hospitalet de Llobregat - 05 Santa Eulàlia Nord
202,75,Barcelona Metropolitana Sud,293,L'Hospitalet de Llobregat - 06 Santa Eulàlia Sud
203,75,Barcelona Metropolitana Sud,294,L'Hospitalet de Llobregat - 07 Florida Nord
204,75,Barcelona Metropolitana Sud,295,L'Hospitalet de Llobregat - 08 Florida Sud
205,75,Barcelona Metropolitana Sud,296,L'Hospitalet de Llobregat - 09 Pubilla Cases
206,75,Barcelona Metropolitana Sud,297,L'Hospitalet de Llobregat - 10 Can Serra
207,75,Barcelona Metropolitana Sud,298,L'Hospitalet de Llobregat - 11 Gornal
208,75,Barcelona Metropolitana Sud,299,L'Hospitalet de Llobregat - 12 Bellvitge
209,75,Barcelona Metropolitana Sud,360,Martorell rural
210,75,Barcelona Metropolitana Sud,365,Castelldefels - 1
211,75,Barcelona Metropolitana Sud,366,Castelldefels - 2
212,75,Barcelona Metropolitana Sud,367,Pallejà
213,75,Barcelona Metropolitana Sud,369,Corbera de Llobregat
214,75,Barcelona Metropolitana Sud,370,Abrera
215,75,Barcelona Metropolitana Sud,373,Begues
216,75,Barcelona Metropolitana Sud,374,Sant Vicenç dels Horts - 1
217,75,Barcelona Metropolitana Sud,375,Sant Vicenç dels Horts - 2
218,75,Barcelona Metropolitana Sud,401,Viladecans - 3
219,76,Barcelona Metropolitana Nord,9,Arenys de Mar
220,76,Barcelona Metropolitana Nord,10,Argentona
221,76,Barcelona Metropolitana Nord,89,Caldes de Montbui
222,76,Barcelona Metropolitana Nord,95,Cardedeu
223,76,Barcelona Metropolitana Nord,97,Castellar del Vallès
224,76,Barcelona Metropolitana Nord,104,Cerdanyola del Vallès - 1
225,76,Barcelona Metropolitana Nord,105,Cerdanyola del Vallès - 2
226,76,Barcelona Metropolitana Nord,121,La Garriga
227,76,Barcelona Metropolitana Nord,150,Martorelles
228,76,Barcelona Metropolitana Nord,152,Mataró - 1
229,76,Barcelona Metropolitana Nord,153,Mataró - 2
230,76,Barcelona Metropolitana Nord,154,Mataró - 3
231,76,Barcelona Metropolitana Nord,155,Mataró - 4
232,76,Barcelona Metropolitana Nord,156,Mataró - 5
233,76,Barcelona Metropolitana Nord,157,Mataró - 6
234,76,Barcelona Metropolitana Nord,158,Mataró - 7
235,76,Barcelona Metropolitana Nord,164,Montornès - Montmeló
236,76,Barcelona Metropolitana Nord,175,Parets del Vallès
237,76,Barcelona Metropolitana Nord,186,Premià de Mar
238,76,Barcelona Metropolitana Nord,190,Sabadell - 1A
239,76,Barcelona Metropolitana Nord,191,Sabadell - 1B
240,76,Barcelona Metropolitana Nord,192,Sabadell - 2
241,76,Barcelona Metropolitana Nord,193,Sabadell - 3A
242,76,Barcelona Metropolitana Nord,194,Sabadell - 3B
243,76,Barcelona Metropolitana Nord,196,Sabadell - 5
244,76,Barcelona Metropolitana Nord,197,Sabadell - 6
245,76,Barcelona Metropolitana Nord,198,Sabadell - 7
246,76,Barcelona Metropolitana Nord,207,Sant Celoni
247,76,Barcelona Metropolitana Nord,222,Santa Coloma de Gramenet - 1
248,76,Barcelona Metropolitana Nord,223,Santa Coloma de Gramenet - 2
249,76,Barcelona Metropolitana Nord,224,Santa Coloma de Gramenet - 3
250,76,Barcelona Metropolitana Nord,225,Santa Coloma de Gramenet - 4
251,76,Barcelona Metropolitana Nord,226,Santa Coloma de Gramenet - 5
252,76,Barcelona Metropolitana Nord,230,Santa Perpètua de Mogoda
253,76,Barcelona Metropolitana Nord,247,Terrassa - A
254,76,Barcelona Metropolitana Nord,248,Terrassa - B
255,76,Barcelona Metropolitana Nord,249,Terrassa - C
256,76,Barcelona Metropolitana Nord,250,Terrassa - D
257,76,Barcelona Metropolitana Nord,251,Terrassa - E
258,76,Barcelona Metropolitana Nord,252,Terrassa - F
259,76,Barcelona Metropolitana Nord,271,Vilassar de Mar
260,76,Barcelona Metropolitana Nord,272,Badalona - 01
261,76,Barcelona Metropolitana Nord,273,Badalona - 02
262,76,Barcelona Metropolitana Nord,274,Badalona - 03
263,76,Barcelona Metropolitana Nord,275,Badalona - 04
264,76,Barcelona Metropolitana Nord,276,Badalona - 05
265,76,Barcelona Metropolitana Nord,277,Badalona - 06
266,76,Barcelona Metropolitana Nord,279,Badalona - 08
267,76,Barcelona Metropolitana Nord,280,Badalona - 09
268,76,Barcelona Metropolitana Nord,281,Badalona - 10
269,76,Barcelona Metropolitana Nord,282,Badalona - 11
270,76,Barcelona Metropolitana Nord,283,Badalona - 12
271,76,Barcelona Metropolitana Nord,284,Granollers - 1 Oest
272,76,Barcelona Metropolitana Nord,285,Granollers - 2 Nord
273,76,Barcelona Metropolitana Nord,286,Granollers - 3 Centre Est
274,76,Barcelona Metropolitana Nord,287,Granollers - 4 Sud
275,76,Barcelona Metropolitana Nord,300,La Llagosta
276,76,Barcelona Metropolitana Nord,302,Montcada i Reixac
277,76,Barcelona Metropolitana Nord,309,Rubí - 1
278,76,Barcelona Metropolitana Nord,310,Rubí - 2
279,76,Barcelona Metropolitana Nord,311,Sant Adrià de Besòs - 1
280,76,Barcelona Metropolitana Nord,312,Sant Adrià de Besòs - 2
281,76,Barcelona Metropolitana Nord,315,Vall del Tenes
282,76,Barcelona Metropolitana Nord,319,Montgat
283,76,Barcelona Metropolitana Nord,320,Barberà del Vallès
284,76,Barcelona Metropolitana Nord,322,Badia del Vallès
285,76,Barcelona Metropolitana Nord,335,Sant Andreu de Llavaneres
286,76,Barcelona Metropolitana Nord,341,Badalona - 07A
287,76,Barcelona Metropolitana Nord,342,Badalona - 07B
288,76,Barcelona Metropolitana Nord,344,Sabadell - 4A
289,76,Barcelona Metropolitana Nord,345,Sabadell - 4B
290,76,Barcelona Metropolitana Nord,348,Mollet del Vallès - 1 Est
291,76,Barcelona Metropolitana Nord,349,Mollet del Vallès - 2 Oest
292,76,Barcelona Metropolitana Nord,353,Vilassar de Dalt
293,76,Barcelona Metropolitana Nord,355,La Roca del Vallès
294,76,Barcelona Metropolitana Nord,356,Terrassa - G
295,76,Barcelona Metropolitana Nord,361,El Masnou - Alella
296,76,Barcelona Metropolitana Nord,362,Ocata - Teià
297,76,Barcelona Metropolitana Nord,363,Sant Quirze del Vallès
298,76,Barcelona Metropolitana Nord,368,Santa Coloma de Gramenet - 6
299,76,Barcelona Metropolitana Nord,376,Alt Mogent
300,76,Barcelona Metropolitana Nord,378,Rubí - 3
301,76,Barcelona Metropolitana Nord,384,Cerdanyola - Ripollet
302,76,Barcelona Metropolitana Nord,386,Ripollet - 1
303,76,Barcelona Metropolitana Nord,387,Ripollet - 2
304,76,Barcelona Metropolitana Nord,388,Sant Cugat del Vallès - 1
305,76,Barcelona Metropolitana Nord,389,Sant Cugat del Vallès - 2
306,76,Barcelona Metropolitana Nord,390,Sant Cugat del Vallès - 3
307,76,Barcelona Metropolitana Nord,391,Palau-solità i Plegamans
308,76,Barcelona Metropolitana Nord,392,Polinyà - Sentmenat
309,76,Barcelona Metropolitana Nord,399,Castellbisbal
310,76,Barcelona Metropolitana Nord,404,Terrassa - H
311,79,Barcelona Ciutat,16,Barcelona - 01A
312,79,Barcelona Ciutat,17,Barcelona - 01B
313,79,Barcelona Ciutat,18,Barcelona - 01C
314,79,Barcelona Ciutat,19,Barcelona - 01D
315,79,Barcelona Ciutat,20,Barcelona - 01E
316,79,Barcelona Ciutat,21,Barcelona - 02A
317,79,Barcelona Ciutat,22,Barcelona - 02B
318,79,Barcelona Ciutat,23,Barcelona - 02C
319,79,Barcelona Ciutat,24,Barcelona - 02D
320,79,Barcelona Ciutat,25,Barcelona - 02E
321,79,Barcelona Ciutat,27,Barcelona - 02G
322,79,Barcelona Ciutat,28,Barcelona - 02H
323,79,Barcelona Ciutat,29,Barcelona - 02I
324,79,Barcelona Ciutat,30,Barcelona - 02J
325,79,Barcelona Ciutat,31,Barcelona - 02K
326,79,Barcelona Ciutat,32,Barcelona - 03A
327,79,Barcelona Ciutat,33,Barcelona - 03B
328,79,Barcelona Ciutat,34,Barcelona - 03C
329,79,Barcelona Ciutat,35,Barcelona - 03D
330,79,Barcelona Ciutat,36,Barcelona - 03E
331,79,Barcelona Ciutat,38,Barcelona - 03G
332,79,Barcelona Ciutat,39,Barcelona - 04A
333,79,Barcelona Ciutat,40,Barcelona - 04B
334,79,Barcelona Ciutat,41,Barcelona - 04C
335,79,Barcelona Ciutat,42,Barcelona - 05A
336,79,Barcelona Ciutat,43,Barcelona - 05B
337,79,Barcelona Ciutat,44,Barcelona - 05C
338,79,Barcelona Ciutat,45,Barcelona - 05D
339,79,Barcelona Ciutat,46,Barcelona - 05E
340,79,Barcelona Ciutat,47,Barcelona - 06A
341,79,Barcelona Ciutat,48,Barcelona - 06B
342,79,Barcelona Ciutat,49,Barcelona - 06C
343,79,Barcelona Ciutat,50,Barcelona - 06D
344,79,Barcelona Ciutat,51,Barcelona - 07A
345,79,Barcelona Ciutat,52,Barcelona - 07B
346,79,Barcelona Ciutat,53,Barcelona - 07C
347,79,Barcelona Ciutat,54,Barcelona - 07D
348,79,Barcelona Ciutat,55,Barcelona - 07E
349,79,Barcelona Ciutat,56,Barcelona - 07F
350,79,Barcelona Ciutat,59,Barcelona - 08C
351,79,Barcelona Ciutat,62,Barcelona - 08F
352,79,Barcelona Ciutat,63,Barcelona - 08G
353,79,Barcelona Ciutat,64,Barcelona - 08H
354,79,Barcelona Ciutat,65,Barcelona - 09A
355,79,Barcelona Ciutat,67,Barcelona - 09C
356,79,Barcelona Ciutat,69,Barcelona - 09E
357,79,Barcelona Ciutat,70,Barcelona - 09F
358,79,Barcelona Ciutat,71,Barcelona - 10A
359,79,Barcelona Ciutat,72,Barcelona - 10B
360,79,Barcelona Ciutat,73,Barcelona - 10C
361,79,Barcelona Ciutat,74,Barcelona - 10D
362,79,Barcelona Ciutat,75,Barcelona - 10E
363,79,Barcelona Ciutat,76,Barcelona - 10F
364,79,Barcelona Ciutat,77,Barcelona - 10G
365,79,Barcelona Ciutat,78,Barcelona - 10H
366,79,Barcelona Ciutat,79,Barcelona - 10I
367,79,Barcelona Ciutat,326,Barcelona - 07G
368,79,Barcelona Ciutat,327,Barcelona - 08I
369,79,Barcelona Ciutat,331,Barcelona - 10J
370,79,Barcelona Ciutat,358,Barcelona - 06E
371,79,Barcelona Ciutat,383,Barcelona - 03H
372,79,Barcelona Ciutat,385,Barcelona - 08J
373,79,Barcelona Ciutat,395,Barcelona - 09H
374,79,Barcelona Ciutat,396,Barcelona - 09I
375,79,Barcelona Ciutat,400,Barcelona - 03I
376,79,Barcelona Ciutat,402,Barcelona - 08K
377,79,Barcelona Ciutat,403,Barcelona - 08L

--- DESCARREGADOR DADES SIVIC (OPENAIR FORMAT) ---
ℹ️  Utilitza els codis de regions i CAPs dels CSV descarregats.
   Si deixes buit, selecciona tots.
----------------------------------------------------
Introdueix l'any inici (deixa buit per tots):
Introdueix l'any fi (deixa buit si igual a inici):
Introdueix Codi Regió (ex: 76): 75
Introdueix Codi ABS/CAP (ex: 310): 149
🚀 Iniciant descàrrega de dades SIVIC...
   Filtres -> Anys: None a None, Regió: 75, ABS/CAP: 149
📥 50000 registres processats... Data actual: 2018-05-24
📥 100000 registres processats... Data actual: 2024-10-27
📥 150000 registres processats... Data actual: 2026-02-08

✅ ÈXIT: 111979 registres descarregats.
📅 Període: 2011-10-03 fins a 2026-02-08

In [ ]:
import pandas as pd
import time
import urllib.parse
from google.colab import files
from datetime import datetime

def descarregar_filtrat(any_seleccionat=None, codi_regio=None, codi_abs=None):
    """
    Descarrega dades filtrant per any, codi_regio i/o codi_abs.
    """
    base_url = "https://analisi.transparenciacatalunya.cat/resource/fa7i-d8gc.json"
    limit = 50000
    offset = 0
    tots_els_dades = []

    # Construir condicions SoQL
    condicions = []
    if codi_regio:
        condicions.append(f"codi_regio='{codi_regio}'")
    if codi_abs:
        condicions.append(f"codi_abs='{codi_abs}'")
    if any_seleccionat:
        data_inici = f"{any_seleccionat}-01-01T00:00:00"
        data_fi = f"{any_seleccionat+1}-01-01T00:00:00"
        condicions.append(f"data >= '{data_inici}' AND data < '{data_fi}'")

    where_clause = " AND ".join(condicions) if condicions else "1=1"  # 1=1 per agafar tot si no hi ha filtre

    print("🚀 Iniciant descàrrega amb els filtres:")
    print(f"   Any: {any_seleccionat}, codi_regio: {codi_regio}, codi_abs: {codi_abs}")

    while True:
        query = f"?$where={where_clause}&$limit={limit}&$offset={offset}&$order=data ASC"
        url_neta = base_url + urllib.parse.quote(query, safe='?=&-:T')

        try:
            df_bloc = pd.read_json(url_neta)

            if df_bloc.empty:
                break

            tots_els_dades.append(df_bloc)
            offset += limit

            ultima_data = df_bloc['data'].iloc[-1]
            print(f"📥 {offset} registres obtinguts... Arribant a la data: {ultima_data[:10]}")

            time.sleep(0.5)

        except Exception as e:
            print(f"⚠️ Error durant la descàrrega: {e}")
            break

    if tots_els_dades:
        df_final = pd.concat(tots_els_dades, ignore_index=True)
        df_final['data'] = pd.to_datetime(df_final['data'])

        print(f"\n✅ ÈXIT: {len(df_final)} registres descarregats.")
        print(f"📅 Període: {df_final['data'].min().date()} fins a {df_final['data'].max().date()}")

        # Nom de fitxer basat en filtres
        nom_fitxer = f"SIVIC"
        if codi_regio: nom_fitxer += f"_regio_{codi_regio}"
        if codi_abs: nom_fitxer += f"_abs_{codi_abs}"
        if any_seleccionat: nom_fitxer += f"_{any_seleccionat}"
        nom_fitxer += ".csv"

        df_final.to_csv(nom_fitxer, index=False)
        files.download(nom_fitxer)

        return df_final
    else:
        print("❌ No s'han pogut recuperar dades.")
        return None

# Exemple d'ús
any_usuari = input("Introdueix l'any (deixa buit per tots): ").strip()
codi_regio_usuari = input("Introdueix codi_regio (deixa buit per tots): ").strip()
codi_abs_usuari = input("Introdueix codi_abs (deixa buit per tots): ").strip()

any_usuari = int(any_usuari) if any_usuari else None
codi_regio_usuari = codi_regio_usuari if codi_regio_usuari else None
codi_abs_usuari = codi_abs_usuari if codi_abs_usuari else None

df_resultat = descarregar_filtrat(any_usuari, codi_regio_usuari, codi_abs_usuari)

Introdueix l'any (deixa buit per tots):
Introdueix codi_regio (deixa buit per tots): 75
Introdueix codi_abs (deixa buit per tots): 149
🚀 Iniciant descàrrega amb els filtres:
   Any: None, codi_regio: 75, codi_abs: 149
📥 50000 registres obtinguts... Arribant a la data: 2018-05-24
📥 100000 registres obtinguts... Arribant a la data: 2024-10-27
📥 150000 registres obtinguts... Arribant a la data: 2026-02-08

✅ ÈXIT: 111979 registres descarregats.
📅 Període: 2011-10-03 fins a 2026-02-08

In [ ]:

import pandas as pd
from google.colab import files
import urllib.parse

base_url = "https://analisi.transparenciacatalunya.cat/resource/fa7i-d8gc.json"

# Per regions
query_regions = "?$select=codi_regio,nom_regio&$group=codi_regio,nom_regio&$order=codi_regio ASC&$limit=1000"
url_regions = base_url + urllib.parse.quote(query_regions, safe='?=&$')
df_regions = pd.read_json(url_regions)
df_regions.to_csv('regions.csv', index=False)
files.download('regions.csv')

# Per ABS/CAPs
query_abs = "?$select=codi_regio,nom_regio,codi_abs,nom_abs&$group=codi_regio,nom_regio,codi_abs,nom_abs&$order=codi_regio,codi_abs ASC&$limit=100000"
url_abs = base_url + urllib.parse.quote(query_abs, safe='?=&$')
df_abs = pd.read_json(url_abs)
df_abs.to_csv('caps.csv', index=False)
files.download('caps.csv')

# Mostrar completament
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

display(df_regions)
display(df_abs)

    codi_regio                     nom_regio
0            0                 No disponible
1           61                        Lleida
2           62             Camp de Tarragona
3           63              Terres de l'Ebre
4           64                        Girona
5           67             Catalunya Central
6           70                       Penedès
7           71            Alt Pirineu i Aran
8           75   Barcelona Metropolitana Sud
9           76  Barcelona Metropolitana Nord
10          79              Barcelona Ciutat

,codi_regio,nom_regio,codi_abs,nom_abs
0,0,No disponible,0,No disponible
1,61,Lleida,1,Agramunt
2,61,Lleida,2,Alcarràs
3,61,Lleida,3,Alfarràs - Almenar
4,61,Lleida,12,Artesa de Segre
5,61,Lleida,14,Balaguer
6,61,Lleida,81,Bellpuig
7,61,Lleida,86,Les Borges Blanques
8,61,Lleida,106,Cervera - la Segarra
9,61,Lleida,129,La Granadella
10,61,Lleida,135,Lleida - 1 Centre Històric - Rambla de Ferran
11,61,Lleida,136,Lleida - 2 Ronda - Mariola
12,61,Lleida,137,Lleida - 3 Eixample
13,61,Lleida,138,Lleida - 4 Balàfia - Pardinyes
14,61,Lleida,139,Lleida - 5 Cappont
15,61,Lleida,140,Lleida - 6 Bordeta - Magraners
16,61,Lleida,141,Lleida rural - 1 Nord
17,61,Lleida,161,Pla d'Urgell
18,61,Lleida,181,Ponts
19,61,Lleida,232,Seròs
20,61,Lleida,245,Tàrrega
21,61,Lleida,329,Lleida rural - 2 Sud
22,61,Lleida,334,Almacelles
23,61,Lleida,379,Lleida - 7 Onze de Setembre
24,61,Lleida,408,Guissona - La Segarra
25,62,Camp de Tarragona,87,Les Borges del Camp
26,62,Camp de Tarragona,91,Cambrils
27,62,Camp de Tarragona,107,Constantí
28,62,Camp de Tarragona,112,Cornudella de Montsant
29,62,Camp de Tarragona,118,Falset
30,62,Camp de Tarragona,162,Montblanc
31,62,Camp de Tarragona,163,Mont-roig del Camp
32,62,Camp de Tarragona,166,El Morell
33,62,Camp de Tarragona,188,Riudoms
34,62,Camp de Tarragona,239,Tarragona - 1
35,62,Camp de Tarragona,240,Tarragona - 2
36,62,Camp de Tarragona,241,Tarragona - 3
37,62,Camp de Tarragona,242,Tarragona - 4
38,62,Camp de Tarragona,243,Tarragona - 5
39,62,Camp de Tarragona,244,Tarragona - 6
40,62,Camp de Tarragona,257,Torredembarra
41,62,Camp de Tarragona,262,Alt Camp Est
42,62,Camp de Tarragona,263,Valls urbà
43,62,Camp de Tarragona,303,Reus - 1
44,62,Camp de Tarragona,304,Reus - 2
45,62,Camp de Tarragona,305,Reus - 3
46,62,Camp de Tarragona,306,Reus - 4
47,62,Camp de Tarragona,307,Reus - 5
48,62,Camp de Tarragona,324,Vandellòs i l'Hospitalet de l'Infant
49,62,Camp de Tarragona,333,Alt Camp Oest
50,62,Camp de Tarragona,339,Salou
51,62,Camp de Tarragona,340,Vila-seca
52,62,Camp de Tarragona,352,Tarragona - 7
53,62,Camp de Tarragona,354,La Selva del Camp
54,62,Camp de Tarragona,364,Tarragona - 8
55,63,Terres de l'Ebre,4,Amposta
56,63,Terres de l'Ebre,113,Deltebre
57,63,Terres de l'Ebre,120,Flix
58,63,Terres de l'Ebre,165,Móra la Nova - Móra d'Ebre
59,63,Terres de l'Ebre,178,L'Ametlla de Mar - El Perelló
60,63,Terres de l'Ebre,206,La Ràpita - Alcanar
61,63,Terres de l'Ebre,246,Terra Alta
62,63,Terres de l'Ebre,255,Tortosa - 1 Est
63,63,Terres de l'Ebre,256,Tortosa - 2 Oest
64,63,Terres de l'Ebre,260,Ulldecona
65,63,Terres de l'Ebre,328,L'Aldea - Camarles - l'Ampolla
66,64,Girona,5,Anglès
67,64,Girona,8,Arbúcies - Sant Hilari
68,64,Girona,15,Banyoles
69,64,Girona,80,Bàscara
70,64,Girona,83,Besalú
71,64,Girona,84,La Bisbal d'Empordà
72,64,Girona,85,Blanes
73,64,Girona,90,Calella
74,64,Girona,92,Camprodon
75,64,Girona,93,Canet de Mar
76,64,Girona,100,Cassà de la Selva
77,64,Girona,101,Celrà
78,64,Girona,114,L'Escala
79,64,Girona,119,Figueres
80,64,Girona,124,Girona - 1
81,64,Girona,125,Girona - 2
82,64,Girona,126,Girona - 3
83,64,Girona,127,Girona - 4
84,64,Girona,133,La Jonquera
85,64,Girona,134,Llançà
86,64,Girona,142,Lloret de Mar
87,64,Girona,143,Malgrat de Mar
88,64,Girona,171,Olot
89,64,Girona,172,Palafrugell
90,64,Girona,173,Palamós
91,64,Girona,177,Peralada
92,64,Girona,187,Ripoll - Sant Joan de les Abadesses
93,64,Girona,189,Roses
94,64,Girona,199,Salt
95,64,Girona,208,Sant Feliu de Guíxols
96,64,Girona,221,Santa Coloma de Farners
97,64,Girona,231,Sarrià de Ter
98,64,Girona,234,Sils - Vidreres - Maçanet de la Selva
99,64,Girona,258,Torroella de Montgrí
100,64,Girona,267,Vilafant
101,64,Girona,325,Pineda de Mar
102,64,Girona,330,Breda - Hostalric
103,64,Girona,336,Tordera
104,64,Girona,343,Ribes de Freser - Campdevànol
105,64,Girona,346,Sant Joan les Fonts
106,64,Girona,347,Vall d'en Bas
107,67,Catalunya Central,11,Artés
108,67,Catalunya Central,82,Berga
109,67,Catalunya Central,88,Calaf
110,67,Catalunya Central,96,Cardona
111,67,Catalunya Central,98,Montserrat
112,67,Catalunya Central,102,Centelles
113,67,Catalunya Central,128,Baix Berguedà
114,67,Catalunya Central,130,Alt Berguedà
115,67,Catalunya Central,144,Manlleu
116,67,Catalunya Central,145,Manresa - 1
117,67,Catalunya Central,146,Manresa - 2
118,67,Catalunya Central,147,Manresa - 3
119,67,Catalunya Central,148,Manresa - 4
120,67,Catalunya Central,159,Moià
121,67,Catalunya Central,167,Navàs - Balsareny
122,67,Catalunya Central,185,Lluçanès
123,67,Catalunya Central,200,Sallent
124,67,Catalunya Central,211,Navarcles - Sant Fruitós de Bages
125,67,Catalunya Central,212,Sant Hipólit de Voltregà
126,67,Catalunya Central,215,Sant Joan de Vilatorrada
127,67,Catalunya Central,217,Sant Quirze de Besora
128,67,Catalunya Central,219,Sant Vicenç de Castellet
129,67,Catalunya Central,236,El Solsonès
130,67,Catalunya Central,237,Súria
131,67,Catalunya Central,238,Santa Eugènia de Berga
132,67,Catalunya Central,253,Tona
133,67,Catalunya Central,254,Vall del Ges
134,67,Catalunya Central,350,Vic - 1 Nord
135,67,Catalunya Central,351,Vic - 2 Sud
136,67,Catalunya Central,377,Roda de Ter
137,67,Catalunya Central,409,Santpedor
138,70,Penedès,13,El Vendrell
139,70,Penedès,131,Anoia rural
140,70,Penedès,218,Sant Sadurní d'Anoia
141,70,Penedès,228,Santa Coloma de Queralt
142,70,Penedès,229,Santa Margarida de Montbui
143,70,Penedès,235,Sitges
144,70,Penedès,269,Vilanova del Camí
145,70,Penedès,314,Baix Penedès - Interior
146,70,Penedès,316,Vilanova i la Geltrú - 1
147,70,Penedès,317,Vilanova i la Geltrú - 2
148,70,Penedès,337,Capellades
149,70,Penedès,338,Piera
150,70,Penedès,357,Calafell
151,70,Penedès,359,Cubelles - Cunit
152,70,Penedès,371,Igualada - 1
153,70,Penedès,372,Igualada - 2
154,70,Penedès,380,Vilanova i la Geltrú - 3
155,70,Penedès,393,Ribes - Olivella
156,70,Penedès,394,Roquetes - Canyelles
157,70,Penedès,397,Vilafranca del Penedès - 1
158,70,Penedès,398,Vilafranca del Penedès - 2
159,70,Penedès,405,Penedès rural - Est
160,70,Penedès,406,Penedès rural - Oest
161,71,Alt Pirineu i Aran,7,Aran
162,71,Alt Pirineu i Aran,103,Cerdanya
163,71,Alt Pirineu i Aran,169,Alt Urgell Sud
164,71,Alt Pirineu i Aran,174,Pallars Sobirà
165,71,Alt Pirineu i Aran,179,La Pobla de Segur
166,71,Alt Pirineu i Aran,180,Alta Ribagorça
167,71,Alt Pirineu i Aran,233,La Seu d'Urgell
168,71,Alt Pirineu i Aran,259,Tremp
169,75,Barcelona Metropolitana Sud,108,Cornellà de Llobregat - 1
170,75,Barcelona Metropolitana Sud,109,Cornellà de Llobregat - 2
171,75,Barcelona Metropolitana Sud,110,Cornellà de Llobregat - 3
172,75,Barcelona Metropolitana Sud,111,Cornellà de Llobregat - 4
173,75,Barcelona Metropolitana Sud,115,Esparreguera
174,75,Barcelona Metropolitana Sud,116,Esplugues de Llobregat - 1
175,75,Barcelona Metropolitana Sud,117,Esplugues de Llobregat - 2
176,75,Barcelona Metropolitana Sud,122,Gavà - 1
177,75,Barcelona Metropolitana Sud,123,Gavà - 2
178,75,Barcelona Metropolitana Sud,149,Martorell
179,75,Barcelona Metropolitana Sud,160,Molins de Rei
180,75,Barcelona Metropolitana Sud,168,Olesa de Montserrat
181,75,Barcelona Metropolitana Sud,182,El Prat de Llobregat - 1
182,75,Barcelona Metropolitana Sud,183,El Prat de Llobregat - 2
183,75,Barcelona Metropolitana Sud,184,El Prat de Llobregat - 3
184,75,Barcelona Metropolitana Sud,201,Sant Andreu de la Barca
185,75,Barcelona Metropolitana Sud,202,Sant Boi de Llobregat - 1
186,75,Barcelona Metropolitana Sud,203,Sant Boi de Llobregat - 2
187,75,Barcelona Metropolitana Sud,204,Sant Boi de Llobregat - 3
188,75,Barcelona Metropolitana Sud,205,Sant Boi de Llobregat - 4
189,75,Barcelona Metropolitana Sud,209,Sant Feliu de Llobregat - 1
190,75,Barcelona Metropolitana Sud,210,Sant Feliu de Llobregat - 2
191,75,Barcelona Metropolitana Sud,213,Sant Joan Despí - 1
192,75,Barcelona Metropolitana Sud,214,Sant Joan Despí - 2
193,75,Barcelona Metropolitana Sud,216,Sant Just Desvern
194,75,Barcelona Metropolitana Sud,261,Vallirana
195,75,Barcelona Metropolitana Sud,265,Viladecans - 1
196,75,Barcelona Metropolitana Sud,266,Viladecans - 2
197,75,Barcelona Metropolitana Sud,288,L'Hospitalet de Llobregat - 01 Centre
198,75,Barcelona Metropolitana Sud,289,L'Hospitalet de Llobregat - 02 Sant Josep
199,75,Barcelona Metropolitana Sud,290,L'Hospitalet de Llobregat - 03 Colblanc
200,75,Barcelona Metropolitana Sud,291,L'Hospitalet de Llobregat - 04 Torrassa
201,75,Barcelona Metropolitana Sud,292,L'Hospitalet de Llobregat - 05 Santa Eulàlia Nord
202,75,Barcelona Metropolitana Sud,293,L'Hospitalet de Llobregat - 06 Santa Eulàlia Sud
203,75,Barcelona Metropolitana Sud,294,L'Hospitalet de Llobregat - 07 Florida Nord
204,75,Barcelona Metropolitana Sud,295,L'Hospitalet de Llobregat - 08 Florida Sud
205,75,Barcelona Metropolitana Sud,296,L'Hospitalet de Llobregat - 09 Pubilla Cases
206,75,Barcelona Metropolitana Sud,297,L'Hospitalet de Llobregat - 10 Can Serra
207,75,Barcelona Metropolitana Sud,298,L'Hospitalet de Llobregat - 11 Gornal
208,75,Barcelona Metropolitana Sud,299,L'Hospitalet de Llobregat - 12 Bellvitge
209,75,Barcelona Metropolitana Sud,360,Martorell rural
210,75,Barcelona Metropolitana Sud,365,Castelldefels - 1
211,75,Barcelona Metropolitana Sud,366,Castelldefels - 2
212,75,Barcelona Metropolitana Sud,367,Pallejà
213,75,Barcelona Metropolitana Sud,369,Corbera de Llobregat
214,75,Barcelona Metropolitana Sud,370,Abrera
215,75,Barcelona Metropolitana Sud,373,Begues
216,75,Barcelona Metropolitana Sud,374,Sant Vicenç dels Horts - 1
217,75,Barcelona Metropolitana Sud,375,Sant Vicenç dels Horts - 2
218,75,Barcelona Metropolitana Sud,401,Viladecans - 3
219,76,Barcelona Metropolitana Nord,9,Arenys de Mar
220,76,Barcelona Metropolitana Nord,10,Argentona
221,76,Barcelona Metropolitana Nord,89,Caldes de Montbui
222,76,Barcelona Metropolitana Nord,95,Cardedeu
223,76,Barcelona Metropolitana Nord,97,Castellar del Vallès
224,76,Barcelona Metropolitana Nord,104,Cerdanyola del Vallès - 1
225,76,Barcelona Metropolitana Nord,105,Cerdanyola del Vallès - 2
226,76,Barcelona Metropolitana Nord,121,La Garriga
227,76,Barcelona Metropolitana Nord,150,Martorelles
228,76,Barcelona Metropolitana Nord,152,Mataró - 1
229,76,Barcelona Metropolitana Nord,153,Mataró - 2
230,76,Barcelona Metropolitana Nord,154,Mataró - 3
231,76,Barcelona Metropolitana Nord,155,Mataró - 4
232,76,Barcelona Metropolitana Nord,156,Mataró - 5
233,76,Barcelona Metropolitana Nord,157,Mataró - 6
234,76,Barcelona Metropolitana Nord,158,Mataró - 7
235,76,Barcelona Metropolitana Nord,164,Montornès - Montmeló
236,76,Barcelona Metropolitana Nord,175,Parets del Vallès
237,76,Barcelona Metropolitana Nord,186,Premià de Mar
238,76,Barcelona Metropolitana Nord,190,Sabadell - 1A
239,76,Barcelona Metropolitana Nord,191,Sabadell - 1B
240,76,Barcelona Metropolitana Nord,192,Sabadell - 2
241,76,Barcelona Metropolitana Nord,193,Sabadell - 3A
242,76,Barcelona Metropolitana Nord,194,Sabadell - 3B
243,76,Barcelona Metropolitana Nord,196,Sabadell - 5
244,76,Barcelona Metropolitana Nord,197,Sabadell - 6
245,76,Barcelona Metropolitana Nord,198,Sabadell - 7
246,76,Barcelona Metropolitana Nord,207,Sant Celoni
247,76,Barcelona Metropolitana Nord,222,Santa Coloma de Gramenet - 1
248,76,Barcelona Metropolitana Nord,223,Santa Coloma de Gramenet - 2
249,76,Barcelona Metropolitana Nord,224,Santa Coloma de Gramenet - 3
250,76,Barcelona Metropolitana Nord,225,Santa Coloma de Gramenet - 4
251,76,Barcelona Metropolitana Nord,226,Santa Coloma de Gramenet - 5
252,76,Barcelona Metropolitana Nord,230,Santa Perpètua de Mogoda
253,76,Barcelona Metropolitana Nord,247,Terrassa - A
254,76,Barcelona Metropolitana Nord,248,Terrassa - B
255,76,Barcelona Metropolitana Nord,249,Terrassa - C
256,76,Barcelona Metropolitana Nord,250,Terrassa - D
257,76,Barcelona Metropolitana Nord,251,Terrassa - E
258,76,Barcelona Metropolitana Nord,252,Terrassa - F
259,76,Barcelona Metropolitana Nord,271,Vilassar de Mar
260,76,Barcelona Metropolitana Nord,272,Badalona - 01
261,76,Barcelona Metropolitana Nord,273,Badalona - 02
262,76,Barcelona Metropolitana Nord,274,Badalona - 03
263,76,Barcelona Metropolitana Nord,275,Badalona - 04
264,76,Barcelona Metropolitana Nord,276,Badalona - 05
265,76,Barcelona Metropolitana Nord,277,Badalona - 06
266,76,Barcelona Metropolitana Nord,279,Badalona - 08
267,76,Barcelona Metropolitana Nord,280,Badalona - 09
268,76,Barcelona Metropolitana Nord,281,Badalona - 10
269,76,Barcelona Metropolitana Nord,282,Badalona - 11
270,76,Barcelona Metropolitana Nord,283,Badalona - 12
271,76,Barcelona Metropolitana Nord,284,Granollers - 1 Oest
272,76,Barcelona Metropolitana Nord,285,Granollers - 2 Nord
273,76,Barcelona Metropolitana Nord,286,Granollers - 3 Centre Est
274,76,Barcelona Metropolitana Nord,287,Granollers - 4 Sud
275,76,Barcelona Metropolitana Nord,300,La Llagosta
276,76,Barcelona Metropolitana Nord,302,Montcada i Reixac
277,76,Barcelona Metropolitana Nord,309,Rubí - 1
278,76,Barcelona Metropolitana Nord,310,Rubí - 2
279,76,Barcelona Metropolitana Nord,311,Sant Adrià de Besòs - 1
280,76,Barcelona Metropolitana Nord,312,Sant Adrià de Besòs - 2
281,76,Barcelona Metropolitana Nord,315,Vall del Tenes
282,76,Barcelona Metropolitana Nord,319,Montgat
283,76,Barcelona Metropolitana Nord,320,Barberà del Vallès
284,76,Barcelona Metropolitana Nord,322,Badia del Vallès
285,76,Barcelona Metropolitana Nord,335,Sant Andreu de Llavaneres
286,76,Barcelona Metropolitana Nord,341,Badalona - 07A
287,76,Barcelona Metropolitana Nord,342,Badalona - 07B
288,76,Barcelona Metropolitana Nord,344,Sabadell - 4A
289,76,Barcelona Metropolitana Nord,345,Sabadell - 4B
290,76,Barcelona Metropolitana Nord,348,Mollet del Vallès - 1 Est
291,76,Barcelona Metropolitana Nord,349,Mollet del Vallès - 2 Oest
292,76,Barcelona Metropolitana Nord,353,Vilassar de Dalt
293,76,Barcelona Metropolitana Nord,355,La Roca del Vallès
294,76,Barcelona Metropolitana Nord,356,Terrassa - G
295,76,Barcelona Metropolitana Nord,361,El Masnou - Alella
296,76,Barcelona Metropolitana Nord,362,Ocata - Teià
297,76,Barcelona Metropolitana Nord,363,Sant Quirze del Vallès
298,76,Barcelona Metropolitana Nord,368,Santa Coloma de Gramenet - 6
299,76,Barcelona Metropolitana Nord,376,Alt Mogent
300,76,Barcelona Metropolitana Nord,378,Rubí - 3
301,76,Barcelona Metropolitana Nord,384,Cerdanyola - Ripollet
302,76,Barcelona Metropolitana Nord,386,Ripollet - 1
303,76,Barcelona Metropolitana Nord,387,Ripollet - 2
304,76,Barcelona Metropolitana Nord,388,Sant Cugat del Vallès - 1
305,76,Barcelona Metropolitana Nord,389,Sant Cugat del Vallès - 2
306,76,Barcelona Metropolitana Nord,390,Sant Cugat del Vallès - 3
307,76,Barcelona Metropolitana Nord,391,Palau-solità i Plegamans
308,76,Barcelona Metropolitana Nord,392,Polinyà - Sentmenat
309,76,Barcelona Metropolitana Nord,399,Castellbisbal
310,76,Barcelona Metropolitana Nord,404,Terrassa - H
311,79,Barcelona Ciutat,16,Barcelona - 01A
312,79,Barcelona Ciutat,17,Barcelona - 01B
313,79,Barcelona Ciutat,18,Barcelona - 01C
314,79,Barcelona Ciutat,19,Barcelona - 01D
315,79,Barcelona Ciutat,20,Barcelona - 01E
316,79,Barcelona Ciutat,21,Barcelona - 02A
317,79,Barcelona Ciutat,22,Barcelona - 02B
318,79,Barcelona Ciutat,23,Barcelona - 02C
319,79,Barcelona Ciutat,24,Barcelona - 02D
320,79,Barcelona Ciutat,25,Barcelona - 02E
321,79,Barcelona Ciutat,27,Barcelona - 02G
322,79,Barcelona Ciutat,28,Barcelona - 02H
323,79,Barcelona Ciutat,29,Barcelona - 02I
324,79,Barcelona Ciutat,30,Barcelona - 02J
325,79,Barcelona Ciutat,31,Barcelona - 02K
326,79,Barcelona Ciutat,32,Barcelona - 03A
327,79,Barcelona Ciutat,33,Barcelona - 03B
328,79,Barcelona Ciutat,34,Barcelona - 03C
329,79,Barcelona Ciutat,35,Barcelona - 03D
330,79,Barcelona Ciutat,36,Barcelona - 03E
331,79,Barcelona Ciutat,38,Barcelona - 03G
332,79,Barcelona Ciutat,39,Barcelona - 04A
333,79,Barcelona Ciutat,40,Barcelona - 04B
334,79,Barcelona Ciutat,41,Barcelona - 04C
335,79,Barcelona Ciutat,42,Barcelona - 05A
336,79,Barcelona Ciutat,43,Barcelona - 05B
337,79,Barcelona Ciutat,44,Barcelona - 05C
338,79,Barcelona Ciutat,45,Barcelona - 05D
339,79,Barcelona Ciutat,46,Barcelona - 05E
340,79,Barcelona Ciutat,47,Barcelona - 06A
341,79,Barcelona Ciutat,48,Barcelona - 06B
342,79,Barcelona Ciutat,49,Barcelona - 06C
343,79,Barcelona Ciutat,50,Barcelona - 06D
344,79,Barcelona Ciutat,51,Barcelona - 07A
345,79,Barcelona Ciutat,52,Barcelona - 07B
346,79,Barcelona Ciutat,53,Barcelona - 07C
347,79,Barcelona Ciutat,54,Barcelona - 07D
348,79,Barcelona Ciutat,55,Barcelona - 07E
349,79,Barcelona Ciutat,56,Barcelona - 07F
350,79,Barcelona Ciutat,59,Barcelona - 08C
351,79,Barcelona Ciutat,62,Barcelona - 08F
352,79,Barcelona Ciutat,63,Barcelona - 08G
353,79,Barcelona Ciutat,64,Barcelona - 08H
354,79,Barcelona Ciutat,65,Barcelona - 09A
355,79,Barcelona Ciutat,67,Barcelona - 09C
356,79,Barcelona Ciutat,69,Barcelona - 09E
357,79,Barcelona Ciutat,70,Barcelona - 09F
358,79,Barcelona Ciutat,71,Barcelona - 10A
359,79,Barcelona Ciutat,72,Barcelona - 10B
360,79,Barcelona Ciutat,73,Barcelona - 10C
361,79,Barcelona Ciutat,74,Barcelona - 10D
362,79,Barcelona Ciutat,75,Barcelona - 10E
363,79,Barcelona Ciutat,76,Barcelona - 10F
364,79,Barcelona Ciutat,77,Barcelona - 10G
365,79,Barcelona Ciutat,78,Barcelona - 10H
366,79,Barcelona Ciutat,79,Barcelona - 10I
367,79,Barcelona Ciutat,326,Barcelona - 07G
368,79,Barcelona Ciutat,327,Barcelona - 08I
369,79,Barcelona Ciutat,331,Barcelona - 10J
370,79,Barcelona Ciutat,358,Barcelona - 06E
371,79,Barcelona Ciutat,383,Barcelona - 03H
372,79,Barcelona Ciutat,385,Barcelona - 08J
373,79,Barcelona Ciutat,395,Barcelona - 09H
374,79,Barcelona Ciutat,396,Barcelona - 09I
375,79,Barcelona Ciutat,400,Barcelona - 03I
376,79,Barcelona Ciutat,402,Barcelona - 08K
377,79,Barcelona Ciutat,403,Barcelona - 08L